### PR TITLE
ipq8074: add Linksys MX8500 BDF

### PR DESCRIPTION
**Pull request by testuser7**
Add the BDF for Linksys MX8500.
IPQ8074 and QCN9074 BDF was edited (removed regdomain and updated regdb).

QCN9074 BDF is not compatible with the latest firmware and is currently not working.

### CODE REVIEW

**Comment by testuser7** [comment]
@Ansuel, can you look at the QCN9074 BDF and modify it like you did with the CR1000A?

**Review by OpenWRT-fanboy — APPROVED** [review]

**Review by OpenWRT-fanboy — APPROVED** [review]

**Comment by OpenWRT-fanboy** [comment]
@robimarko, could you please merge this PR? Without it, WiFi does not work, and so people cannot really test this device.

**Review by NTheZone — APPROVED** [review]

**Review by NTheZone — APPROVED** [review]

**Review by NTheZone — APPROVED** [review]

**Review by aspicer — APPROVED** [review]

**Review by frozen-icecube — APPROVED** [review]

**Comment by robimarko** [comment]
Is the QCN9074 BDF working?

**Comment by OpenWRT-fanboy** [comment]
> Is the QCN9074 BDF working?

Nope. 6E doesn't work yet. However, without this PR, no bands work. If you are uncomfortable merging a known buggy QCN9074 BDF, please merge IPQ8074  BDF so that we can at least get the 2.4G and 5G bands working.

@Ansuel did something to make the QCN9074 BDF work on the Verizon CR1000A, but how he did it is a mystery.

**Comment by randyg503** [comment]
FYI, it looks like very recent progress has been made on getting 6 working:

  https://forum.openwrt.org/t/openwrt-support-for-linksys-mx8500/190742/211?u=randyg503

**Comment by OpenWRT-fanboy** [comment]
> FYI, it looks like very recent progress has been made on getting 6 working:
> 
> https://forum.openwrt.org/t/openwrt-support-for-linksys-mx8500/190742/211?u=randyg503

Indeed, @hot21shot has cracked the case! @robimarko, attached is a working QCN9074 BDF.

[board-linksys_mx8500.zip](https://github.com/user-attachments/files/16992460/board-linksys_mx8500.zip)

**Comment by robimarko** [comment]
I have pushed the IPQ8074 BDF as I need to look into what was done but I do not believe that to be the proper "fix" for 6GHz.

**Comment by testuser7** [comment]
@robimarko Thanks!

> Is the QCN9074 BDF working?

I managed to update the BDF for QCN9074 and now the radio works properly.

It is detected as `6g` radio on initialization:
```
config wifi-device 'radio2'
	option type 'mac80211'
	option path 'soc@0/20000000.pci/pci0000:00/0000:00:00.0/0000:01:00.0'
	option band '6g'
	option channel '33'
	option htmode 'HE80'
	option disabled '1'
```

The client can connect:
```
phy2-ap0  ESSID: "6g"
          Access Point: *
          Mode: Master  Channel: 37 (6.135 GHz)  HT Mode: HE160
          Center Channel 1: 47 2: unknown
          Tx-Power: 20 dBm  Link Quality: 70/70
          Signal: -37 dBm  Noise: -104 dBm
          Bit Rate: 2401.9 MBit/s
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ax
          Hardware: 17CB:1104 17CB:1104 [Qualcomm Atheros QCN6024/9024/9074]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy2
```

To be able to connect from the AX210 card I had to set the PSC channel: https://www.arubanetworks.com/techdocs/ArubaOS_8.9.0_Web_Help/Content/arubaos-solutions/6ghz-radio/6ghz-conf-para.htm#Vldchnlnumpsc

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by skylerbunny** [comment]
I think that this board file and merge merged a QCN9074 board file that was created against board ID 164 (a4), and not board ID 162 (a2) (then applied to board id 255 (ff), which is what the MX8500 expects to see). While for the most part the radio will be detected, kernel traces and looping interrupt problems will often happen at initialization time.

This is the kind of thing that "looks good at a glance", but in regular use the issue becomes obvious. I described why I believe this is so in the developers forum. https://forum.openwrt.org/t/openwrt-support-for-linksys-mx8500/190742/369?u=skylerbunny

Could another merge be done that recreates the board file against the newest available, which I think is here https://git.codelinaro.org/clo/qsdk/oss/ath11k-bdf/-/tree/master/QCN9074/hw1.0/WLAN.HK.2.9.0.1/WLAN.HK.2.9.0.1-01977-QCAHKSWPL_SILICONZ-1?ref_type=heads , but does so against board ID 162, and is backported to v24? Anybody who tries to use 6G on the MX8500 is going to have these problems, especially in a mesh scenario.

cc @robimarko @testuser7 @OpenWRT-fanboy

**Comment by testuser7** [comment]
@skylerbunny Are you having issues with your 6G radio when not using mesh?

For MX8500 the BDF file was prepared based on ID 164 (6G_SBS) by the manufacturer. The file is prepared specifically for this device and it is not possible for a generic file to be added to the repository.

SBS stands for Single Band Simultaneous: https://www.cambiumnetworks.com/wp-content/uploads/Enterprise-Wi-Fi-Access-Point_User-Guide_System-Release-6.5.3.pdf#%5B%7B%22num%22%3A82%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C72%2C522.75%2C0%5D

Can you test mesh operation on 80MHz channel width?

**Comment by skylerbunny** [comment]
@testuser7 Unknown on this...I only have one 6G capable device. I imagine AP mode would be fine IF the router successfully initalized the 6G radio (and I didn't see looping oops/traces, which as I said sometimes happens in mesh mode). (And again, if my router makes it PAST the radio initialiation stage about 20 seconds into kernel boot, it IS fine, even in mesh mode...but it has to get that far.)

If you would like me to try the packaged board file (164) done with HE80, I can certainly try that to see if the initalization issues stop. Related: Is there a way (as SBS seems to imply would be done) to tell openwrt in /etc/config/wireless to use 80+80, with two channel sets, so the benefits of 160 MHz would be realized? If so, I think that may also be something I should try.

**Comment by skylerbunny** [comment]
> @skylerbunny ...
> 
> For MX8500 the BDF file was prepared based on ID 164 (6G_SBS) by the manufacturer. The file is prepared specifically for this device and it is not possible for a generic file to be added to the repository.
> 
> Can you test mesh operation on 80MHz channel width?

@testuser7 Okay, this is interesting. Obviously I don't get the same performance, but testing 80MHz with the 164 (supplied) board file seems to at least not (sometimes) cause trace loops and CPU/interrupt issues at initialization time. The issue of course is that this board file OFFERS HE160, so a person would be likely to try to select it for maximum performance.

[WiFi 6 Socs : Differences between QCN9074, QCN9024, QCN9072,QCN6024](https://dev.t-firefly.com/thread-128566-1-1.html) says this (and we know from internal teardown photos that the MX8500 has a QCN9024):

_The QCN9024 is a mid-range SoC that is based on the quad-core ARM Cortex-A53 CPU, but with a slightly lower clock speed of up to 1.8 GHz. It supports 4x4 MU-MIMO and 80 MHz channels, making it suitable for use in smaller networking devices that don't require the same level of performance as the QCN9074._

I don't know what SBS would offer if hostapd/netifd were able to leverage it using parameters...but I don't think (??) OpenWrt+board file are using it currently, if iw info commands are any indication.

All this being said using a hacked up board against 162 seems to allow use of 160 MHz with 802.11s without the router crashing -- but it may not be advisable. The current board file offers 160 but using it in a mesh situation seems to make it difficult for the router to initialize.

80 MHz on 802.11s+batman-adv looks like it's stable so far and I haven't caught it dumping traces or anything up to this point.

**Comment by testuser7** [comment]
For 80+80 mode you can try `HE80+80`. But I didn't check it.
Overall I can't help much because I don't use `802.11s`.

**Comment by skylerbunny** [comment]
I did check this patch out and have some findings that (also) came from dumping the original factory firmware to figure out what they were doing...

VHT/HE80P80 is generally used, I've now discovered, on 5 GHz (generally to avoid 160MHz widths through DFS channel ranges, by splitting to two 80 MHz non-DFS channels). Even the patch above has an "if" in the script that says 'if 6 GHz, don't allocate a second channel'.

The Linksys factory firmware, curiously, has a directory with the 162, 164, (other) boardfile IDs, and a default board file put into /tmp. 162, 164, and the default boardfiles are all deleted, and symlinks are then created from 162 AND 164's filename to the default filename; the default is then replaced by the custom 164 board file you described. This suggests to me that some QCN9024 boards Linksys used came identifying themselves as 162, some as 164, some as 255, and all three were funneled to the same 164 boardfile, so that hack worked around that problem.

ALSO, nothing in Linksys's initialization files for 6G attempts 160MHz at all, or consider channels 1-31 as allowed (only 33 and above). The channel width choices are 20, 40, 80, and "0". That's it. I've seen mini-PCI QCN9024 variants that only allow 33 and above, so maybe this is where this came from (and the "difference" isn't SBS, but allowed 6G channels); if some chips were 162 and others were 164, "calling" them all 164 would probably produce a union of the least functionality possible: channels 33 and above, and (only enforced by scripts) channel width of 80 and below.

In any case, I imagine 160MHz channel widths MIGHT be possible with the 164 board file (as the firmware reports) with some kind of passed parameter like more reserved memory, TID...something. Failing that, 80 MHz widths look stable, and that's what Linksys went with in their own scripts. I've updated the OpenWrt TOH for this router to state that 80 width is stable and channels 33 and above are usable, unless something else changes on this side or with something like memory allocations that would make 160 widths workable.

**Comment by testuser7** [comment]
@skylerbunny I checked and the 80+80 mode can only be used for the `6g` radio in the case of MX8500:
```
root@OpenWrt:~# iwinfo phy0 htmodelist
HT20 HT40 VHT20 VHT40 VHT80 VHT160 HE20 HE40 HE80 HE160 
root@OpenWrt:~# iwinfo phy1 htmodelist
HT20 HT40 HE20 HE40 
root@OpenWrt:~# iwinfo phy2 htmodelist
HE20 HE40 HE80 HE80+80 HE160
```
Are you able to test whether two routers will connect to each other in this mode?
- https://github.com/openwrt/openwrt/pull/18313#issuecomment-2873951508

**Comment by skylerbunny** [comment]
@testuser7 If you can give me a sysupgrade image file that should be capable of it, and methodology to do this, I'd certainly be willing to try in a mesh mode. (I'm guessing you want me to try against an image that is built with pull 18313 to do so.)

**Comment by testuser7** [comment]
@skylerbunny Image you can use (snapshot with LuCI): https://github.com/testuser7/openwrt/releases/download/qualcommax-ipq807x-main-2a88326/openwrt-qualcommax-ipq807x-linksys_mx8500-squashfs-sysupgrade.bin

and configuration:
```
config wifi-device 'radio2'
	option type 'mac80211'
	option path 'soc@0/20000000.pci/pci0000:00/0000:00:00.0/0000:01:00.0'
	option band '6g'
	option channel '37'
	option channel2 '69'
	option htmode 'HE80P80'
	option disabled '0'
	option country 'US'

config wifi-iface 'default_radio2'
	option device 'radio2'
	option network 'lan'
	option mode 'ap'
	option ssid '6g'
	option encryption 'sae'
	option key '***'
```

**Comment by skylerbunny** [comment]
@testuser7 I think I'm in the same situation you are - I believe the AP came up but my phone doesn't connect to it. That may just mean it doesn't understand the mode. The supplied image doesn't have what I'd need to do 802.11s mesh testing, but I suppose this could be released as 'A client that supports it likely works, and mesh can be checked at a later time'?

**Comment by testuser7** [comment]
You can run the AP on one node and scan the network on the other:
```
iw phy2 scan
```
and check if you see AP.

**Comment by skylerbunny** [comment]
> You can run the AP on one node and scan the network on the other:
> 
> ```
> iwinfo phy2 scan
> ```
> 
> and check if you see AP.

Router set up as above:
phy2-ap0  ESSID: "6g"
          Access Point: xx
          Mode: Master  Channel: 37 (6.135 GHz)  HT Mode: HE80+80
          Center Channel 1: 39 2: 71
          Tx-Power: 20 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: -109 dBm
          Bit Rate: unknown
          Encryption: WPA3 SAE (CCMP)
          Type: nl80211  HW Mode(s): 802.11ax
          Hardware: xx [Qualcomm Atheros QCN6024/9024/9074]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy2

Second MX8500 scanning for the AP:
Cell 02 - Address: xx
          ESSID: "6g"
          Mode: Master  Frequency: 6.135 GHz  Band: 6 GHz  Channel: 37
          Signal: -63 dBm  Quality: 47/70
          Encryption: WPA3 SAE (CCMP)
          HT Operation:
                    Primary Channel: 0
                    Secondary Channel Offset: no secondary
                    Channel Width: 20 MHz
                    
The iwinfo phy2 scan on the second router shows the same thing whether I use a configuration of HE80 or HE80P80 on the first.

**Comment by skylerbunny** [comment]
I can also say that I have a Pixel 9 phone that can connect to the AP when it's in HE80 or HE160, but not HE80P80, for what that's worth.

The above with two routers was with an AP that wa patched and a client that wasn't patched with the firmware...but I don't think that would matter as long as all that's needed is 'scanning on HE80P80', which it should know about.

**Comment by testuser7** [comment]
If you see the AP in `HE80P80` mode from the second router, can you set the radio to `sta` mode and try to connect?

**Comment by skylerbunny** [comment]
> If you see the AP in `HE80P80` mode from the second router, can you set the radio to `sta` mode and try to connect?

My general findings seem to be this:
I didn't have any luck in either HE80 or HE80P80 with a sta/ap configuration, which is simply to say that I didn't get it to work, generally. More interesting however is this:

I tried a mesh mode (802.11s) with two MX8500s. In this situation, it didn't seem to matter whether I used a configuration with two channels and HE80P80, or one channel and HE80; in both cases a spectrum analyzer suggested only channel 37 was broadcasting (and iwinfo was also only showing one channel), and the bandwidth available on the mesh was consistent with an HE80/80MHz channel rather than two such channels.

I would be curious to know (as after all, mesh is what I would be most interested in in this case) if HE80P80 can be/should be configured to work with an 802.11s/mesh/batman-adv setup at all, or whether in a mesh (rather than AP), that HE80P80 is simply ignored, and only 'channel' is interpreted, ignoring 'channel2'.

**Pull request merged**
