### PR TITLE
ipq40xx: add BDFs for Linksys WHW03 V1

### PR DESCRIPTION
**Pull request by Lanchon**
BDFs come from latest firmware, version 1.1.19.209880 (2022-06-20):
- /lib/firmware/IPQ4019/v1/FCC/boardData_1_0_IPQ4019_DK04_2G.bin
- /lib/firmware/IPQ4019/v1/FCC/boardData_1_0_IPQ4019_DK04_5G.bin
- /lib/firmware/QCA9888/v1/FCC/boardData_2_0_QCA9888_5G_Y9690_SBS_HB.bin

### CODE REVIEW

**Comment by Lanchon** [comment]
@robimarko @Ansuel

both files for QCA9888 work well, i chose `boardData_2_0_QCA9888_5G_Y9690_SBS_HB.bin` for the PR.

**Comment by Lanchon** [comment]
question: should i add "-fcc" to the variant name even though i am only importing FCC versions?

**Comment by Lanchon** [comment]
hi @testuser7, could you give hand here so i can finish with this port? thanks!

**Comment by testuser7** [comment]
I think there is no need to add `fcc` in the name or to add other versions of BDF.

**Comment by Lanchon** [comment]
@testuser7

cool, thank you! could you merge this then?

**Comment by testuser7** [comment]
I am unable to do this.

**Comment by Lanchon** [comment]
lol i thought you had commit rights. oh well...

**Comment by testuser7** [comment]
@robimarko @Ansuel support for this device is already merged: https://github.com/openwrt/openwrt/pull/15345 so this should also be merged.

**Comment by robimarko** [comment]
Do you have a full bootlog from stock FW?

**Comment by Lanchon** [comment]
> Do you have a full bootlog from stock FW?

@robimarko

V1 bootlog is here: https://forum.openwrt.org/t/guidance-adding-new-device-linksys-velop-whw03/58464/4

stock whw03 bootlogs do not print BDF CRCs.

**Comment by Lanchon** [comment]
@robimarko could we please expedite this so i can finish the port? thanks!

**Comment by robimarko** [comment]
How did you select the DK04 BDF-s and `boardData_2_0_QCA9888_5G_Y9690_SBS_HB` ?

Cause, this board is based of DK07.1 and I have no idea what the reference is for QCA9888 here.
You cannot just select BDF-s randomly

**Comment by testuser7** [comment]
@robimarko There are two files in `/lib/firmware/QCA9888/v1/FCC/` directory that is used:
- `boardData_2_0_QCA9888_5G_Y9690_SBS_HB.bin`
- `boarddata_2.bin`

Do you want to check the second file?

**Comment by Lanchon** [comment]
> How did you select the DK04 BDF-s and `boardData_2_0_QCA9888_5G_Y9690_SBS_HB` ?
> 
> Cause, this board is based of DK07.1 and I have no idea what the reference is for QCA9888 here. You cannot just select BDF-s randomly

well i asked for help in vain, so i based myself on what had been said in the forum for this device and what was merged for V2.

the BDFs come from either of these, which are bit for bit identical stock rom subtrees for V1 and V2 (ie, each stock rom applies to either V1 or V2, but contains firmware for **both** V1 and V2):
- https://github.com/Lanchon/whw03-stock-firmware/tree/main/whw03v1_1.1.19.209880_2022-06-20/rootfs/lib/firmware
- https://github.com/Lanchon/whw03-stock-firmware/tree/main/whw03v2_2.1.19.209783_2022-06-20/rootfs/lib/firmware

now, for V2 you have these commits in openwrt, with BDFs and all:
https://github.com/openwrt/openwrt/commit/9e4ede8344d60d4837e047e9275c21fd2a8f130b
https://github.com/openwrt/firmware_qca-wireless/commit/711d8ea2e3b47b03d74d6be8d09797051ecb3ade

they include two BDFs. i extracted those and compared them to the contents of the stock rom, and i found these matches:
```
FILE: 'board-linksys_whw03v2.qca4019'
FileSize: 24324
FileCRC32: 10f8077b
FileMD5: becd2bfd261ba72c932cdde3bab17cf6

BoardNames[0]: 'bus=ahb,bmi-chip-id=0,bmi-board-id=20,variant=linksys-whw03v2'
BoardLength[0]: 12064
BoardCRC32[0]: 5bfb5970
BoardMD5[0]: 0435269fbb0797bf269b8cb0591e7544

->	./IPQ4019/v2/FCC/boarddata_0.bin: 5bfb5970
	./IPQ4019/v2/FCC/boarddata_1.bin: ad388fa1
	./IPQ4019/v2/FCC/boarddata_2.bin: 11797524
->	./IPQ4019/v2/FCC/boardData_1_0_IPQ4019_DK04_2G.bin: 5bfb5970
	./IPQ4019/v2/FCC/boardData_1_0_IPQ4019_DK04_5G.bin: ad388fa1
	./IPQ4019/v2/FCC/boardData_2_0_QCA9888_5G_Y9690_SBS_HB.bin: 11797524

BoardNames[1]: 'bus=ahb,bmi-chip-id=0,bmi-board-id=21,variant=linksys-whw03v2'
BoardLength[1]: 12064
BoardCRC32[1]: ad388fa1
BoardMD5[1]: 79042d093e81a43c8c790bc124ca4dfc

	./IPQ4019/v2/FCC/boarddata_0.bin: 5bfb5970
->	./IPQ4019/v2/FCC/boarddata_1.bin: ad388fa1
	./IPQ4019/v2/FCC/boarddata_2.bin: 11797524
	./IPQ4019/v2/FCC/boardData_1_0_IPQ4019_DK04_2G.bin: 5bfb5970
->	./IPQ4019/v2/FCC/boardData_1_0_IPQ4019_DK04_5G.bin: ad388fa1
	./IPQ4019/v2/FCC/boardData_2_0_QCA9888_5G_Y9690_SBS_HB.bin: 11797524

=====

FILE: 'board-linksys_whw03v2.qca9888'
FileSize: 12172
FileCRC32: a5768b9a
FileMD5: b8eadfa9ca7ae39ec7a44cc2b94fc9af

BoardNames[0]: 'bus=pci,bmi-chip-id=0,bmi-board-id=23,variant=linksys-whw03v2'
BoardLength[0]: 12064
BoardCRC32[0]: 09087320
BoardMD5[0]: fde89e0dace1652566d96fb9c83b1c61

	./QCA9888/v2/FCC/boarddata_0.bin: 502af47f
	./QCA9888/v2/FCC/boarddata_1.bin: 9abcafa9
->	./QCA9888/v2/FCC/boarddata_2.bin: 09087320
->	./QCA9888/v2/FCC/boardData_2_0_QCA9888_5G_Y9690_SBS_HB.bin: 09087320
```

for V1, i repeated that same file selection. (except that for V1 the equivalent of the last two files above are **different**, so i had to arbitrarily choose one (after getting no help) and i chose the long-named one.)

so if my chosen V1 files are incorrect, same happens to V2 files.

so these files are incorrect? which are the correct ones then? (links to the roms are in this message),

thank you!!

**Comment by testuser7** [comment]
if I'm correct the differences are only in three settings:
- `flag1`
- `minCCAPwrThresh_A`
- `CCAThresh_A`
```
OFFSET      boarddata_2.bin                                                      boardData_2_0_QCA9888_5G_Y9690_SBS_HB.bin
--------------------------------------------------------------------------------
0x00000000  20 2F F0 D5 01 01 12 34 56 78 90 12 4B 83 00 00 |./.....4Vx..K...| \ 20 2F 4A 68 01 01 12 34 56 78 90 12 4B 83 00 00 |./Jh...4Vx..K...|
0x00000010  15 E0 00 00 00 60 00 00 75 77 02 00 00 00 00 00 |.....`..uw......| / 15 E0 00 42 00 60 00 00 75 77 02 00 00 00 00 00 |...B.`..uw......|
*
0x00000120  03 03 03 03 03 03 00 00 B8 FF 00 00 8A D2 00 00 |................| \ 03 03 03 03 03 03 00 00 B0 FF 00 00 8A D2 00 00 |................|
*
0x00000150  00 00 00 00 00 00 00 00 00 00 0A 01 29 02 09 00 |............)...| / B2 FF 00 00 00 00 00 00 00 00 0A 01 29 02 09 00 |............)...|
*
```

**Comment by Lanchon** [comment]
hi @robimarko, should i just close this?

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
