### PR TITLE
ipq8074:add wallys_dr8072v01 BDF

### PR DESCRIPTION
**Pull request by wallystech-Gg**

### CODE REVIEW

**Comment by wallystech-Gg** [comment]
ipq807x:add support for Wallys DR8072A

**Comment by Ansuel** [comment]
@wallystech-Gg I checked the 2 file and I notice they have the same checksum... Are they for real different BDF?

Also missing commit description to both commits... If they are the same BDF then just submit one. Also if they are similar device with only revision changed, make a dtsi or even use the ALTERNATIVE_NAMES feature (if they are the same device with a different name)

**Comment by wallystech-Gg** [comment]
Add BDF for the  wallys_dr8072v01 router

Signed-off-by: Alan Wallys<gxg@wallystech.com>

**Comment by wallystech-Gg** [comment]
Add BDF for the  wallys_dr8072v01 router

**Comment by wallystech-Gg** [comment]
> @wallystech-Gg I checked the 2 file and I notice they have the same checksum... Are they for real different BDF?
> 
> Also missing commit description to both commits... If they are the same BDF then just submit one. Also if they are similar device with only revision changed, make a dtsi or even use the ALTERNATIVE_NAMES feature (if they are the same device with a different name)

Sir, I have updated it. Is it OK now @Ansuel

**Comment by Ansuel** [comment]
@wallystech-Gg Didn't follow what happen your local files. Sorry for that!

**Pull request merged**
