### PR TITLE
ipq6018: update regdb in TPLink EAP610-Outdoor BDF

### PR DESCRIPTION
**Pull request by testuser7**
Update regdb for TPLink EAP610-Outdoor.
Without this update, the error is displayed:
```
[    9.688839] ath11k c000000.wifi: No regulatory rules available in the event info
[    9.688892] ath11k c000000.wifi: failed to extract regulatory info from received event
```

### CODE REVIEW

**Comment by mrnuke** [comment]
My concern with this BFD is that it enables chhannels 169, 173, and 177. Those were disabled in the vendor's BDF, and should not be enabled on a device with a weatherized enclosure, according to:

 * https://docs.fcc.gov/public/attachments/FCC-20-164A1_Rcd.pdf

```
root@eap610-outdoor:~# iw phy0 info |grep '58.. MHz'
                        * 5805 MHz [161] (30.0 dBm)
                        * 5825 MHz [165] (30.0 dBm)
                        * 5845 MHz [169] (30.0 dBm)
                        * 5865 MHz [173] (30.0 dBm)
                        * 5885 MHz [177] (30.0 dBm)
```

**Comment by testuser7** [comment]
You can check whether the radio is broadcasting a signal by setting channels 169, 173 and 177 with the `HE20` option?

**Comment by mrnuke** [comment]
Yes, I can establish an AP and connect clients in any combination:
 * on channels 169, 173, 177 in `HE20` mode
 * channels {173, 177} in `HE40`
 * channels {165, 169, 173, 177} in `HE80` mode

**Comment by testuser7** [comment]
Only the regdb database has been updated. This should have no impact on available channels. But they were not restricted in BDF or calibration data and now after regdb update they are available.

There is an option to limit the available channels for ath10k (`ieee80211-freq-limit`) but I don't know if it can be used for ath11k.

**Comment by testuser7** [comment]
You can try to use this wifi configuration:
```
&wifi {
	ieee80211-freq-limit = <2402000 5835000>;
	qcom,ath11k-calibration-variant = "TP-Link-EAP610-Outdoor";
	status = "okay";
};
```

**Comment by mrnuke** [comment]
> You can try to use this wifi configuration:
> 
> ```
> &wifi {
> 	ieee80211-freq-limit = <2402000 5835000>;
> 	qcom,ath11k-calibration-variant = "TP-Link-EAP610-Outdoor";
> 	status = "okay";
> };
> ```

Unfortunately, that does not limit the channel availability.

**Comment by robimarko** [comment]
@mrnuke ath11k has no support for it, can you give this a try and I will send it upstream:
https://github.com/robimarko/openwrt/commit/2531ce11271b8f74ec64eab030d7ed0d8e1d4a3a

**Comment by robimarko** [comment]
@mrnuke Now that we have way to limit the allowed frequency ranges is it OK to merge this?

**Comment by mrnuke** [comment]
I was looking into taking the regdb from another IPQ6018-based outdoor AP and swapping it into the EAP-610 BDF. We can do the solution proposed herein, if you feel it is superior. I am okay with either.

**Comment by robimarko** [comment]
@mrnuke But if BDF is being updated with updated regulatory release I would prefer that compared to taking probably outdated one from another BDF

**Comment by testuser7** [comment]
> If there were something "newer", I should be able to see a difference with `iw reg get` and / or `iw phy info`, right?

Have you checked all countries? :)

**Comment by mrnuke** [comment]
> Have you checked all countries? :)

Good point!

**Comment by testuser7** [comment]
Some information about the regdb format can be found here: https://github.com/npnet/android-firmware-qti-sdm660/tree/master/wlan_proc/wlan/halphy_tools/host/bdfUtil/qca61x0/bin/Regulatory_python_scripts

**Comment by mrnuke** [comment]
@robimarko, @testuser7, as I alluded to earlier, I am okay with either solution (this BDF or re-modified BDF).

Only downside of restricting the channels in devicetree only is that `iw phy` still shows the channels as enabled, potentially causing an intern at the FCC to freak out and start writing new rules.

**Comment by robimarko** [comment]
@mrnuke The channels should be marked as disabled in iw phy, that is what I experienced when testing on Qnap

**Comment by mrnuke** [comment]
@robimarko, here's what I get

```
# iw phy0 info |grep Freq -A 29
                Frequencies:
                        * 5180 MHz [36] (30.0 dBm)
                        * 5200 MHz [40] (30.0 dBm)
                        * 5220 MHz [44] (30.0 dBm)
                        * 5240 MHz [48] (30.0 dBm)
                        * 5260 MHz [52] (24.0 dBm) (radar detection)
                        * 5280 MHz [56] (24.0 dBm) (radar detection)
                        * 5300 MHz [60] (24.0 dBm) (radar detection)
                        * 5320 MHz [64] (24.0 dBm) (radar detection)
                        * 5500 MHz [100] (24.0 dBm) (radar detection)
                        * 5520 MHz [104] (24.0 dBm) (radar detection)
                        * 5540 MHz [108] (24.0 dBm) (radar detection)
                        * 5560 MHz [112] (24.0 dBm) (radar detection)
                        * 5580 MHz [116] (24.0 dBm) (radar detection)
                        * 5600 MHz [120] (24.0 dBm) (radar detection)
                        * 5620 MHz [124] (24.0 dBm) (radar detection)
                        * 5640 MHz [128] (24.0 dBm) (radar detection)
                        * 5660 MHz [132] (24.0 dBm) (radar detection)
                        * 5680 MHz [136] (24.0 dBm) (radar detection)
                        * 5700 MHz [140] (24.0 dBm) (radar detection)
                        * 5720 MHz [144] (24.0 dBm) (radar detection)
                        * 5745 MHz [149] (30.0 dBm)
                        * 5765 MHz [153] (30.0 dBm)
                        * 5785 MHz [157] (30.0 dBm)
                        * 5805 MHz [161] (30.0 dBm)
                        * 5825 MHz [165] (30.0 dBm)
                        * 5845 MHz [169] (30.0 dBm)
                        * 5865 MHz [173] (30.0 dBm)
                        * 5885 MHz [177] (30.0 dBm)
        valid interface combinations:
```

```
# iw reg get
global
country 00: DFS-UNSET
        (755 - 928 @ 2), (N/A, 20), (N/A), PASSIVE-SCAN
        (2402 - 2472 @ 40), (N/A, 20), (N/A)
        (2457 - 2482 @ 20), (N/A, 20), (N/A), AUTO-BW, PASSIVE-SCAN
        (2474 - 2494 @ 20), (N/A, 20), (N/A), NO-OFDM, PASSIVE-SCAN
        (5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW, PASSIVE-SCAN
        (5490 - 5730 @ 160), (N/A, 20), (0 ms), DFS, PASSIVE-SCAN
        (5735 - 5835 @ 80), (N/A, 20), (N/A), PASSIVE-SCAN
        (57240 - 63720 @ 2160), (N/A, 0), (N/A)

phy#1 (self-managed)
country US: DFS-FCC
        (2402 - 2472 @ 40), (6, 30), (N/A)
        (5170 - 5250 @ 80), (6, 30), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (6, 24), (0 ms), DFS, AUTO-BW
        (5490 - 5730 @ 160), (6, 24), (0 ms), DFS, AUTO-BW
        (5735 - 5895 @ 160), (6, 30), (N/A), AUTO-BW

phy#0 (self-managed)
country US: DFS-FCC
        (2402 - 2472 @ 40), (6, 30), (N/A)
        (5170 - 5250 @ 80), (6, 30), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (6, 24), (0 ms), DFS, AUTO-BW
        (5490 - 5730 @ 160), (6, 24), (0 ms), DFS, AUTO-BW
        (5735 - 5895 @ 160), (6, 30), (N/A), AUTO-BW

```

**Comment by testuser7** [comment]
@mrnuke Can you check with the country set to `US`?

**Comment by mrnuke** [comment]
I made a testing mistake. `iw phy` shows the correct info. It's just `iw reg get` that shows something else.

```
# iw phy0 info |grep Freq -A 29
                Frequencies:
                        * 5180 MHz [36] (30.0 dBm)
                        * 5200 MHz [40] (30.0 dBm)
                        * 5220 MHz [44] (30.0 dBm)
                        * 5240 MHz [48] (30.0 dBm)
                        * 5260 MHz [52] (24.0 dBm) (radar detection)
                        * 5280 MHz [56] (24.0 dBm) (radar detection)
                        * 5300 MHz [60] (24.0 dBm) (radar detection)
                        * 5320 MHz [64] (24.0 dBm) (radar detection)
                        * 5500 MHz [100] (24.0 dBm) (radar detection)
                        * 5520 MHz [104] (24.0 dBm) (radar detection)
                        * 5540 MHz [108] (24.0 dBm) (radar detection)
                        * 5560 MHz [112] (24.0 dBm) (radar detection)
                        * 5580 MHz [116] (24.0 dBm) (radar detection)
                        * 5600 MHz [120] (24.0 dBm) (radar detection)
                        * 5620 MHz [124] (24.0 dBm) (radar detection)
                        * 5640 MHz [128] (24.0 dBm) (radar detection)
                        * 5660 MHz [132] (24.0 dBm) (radar detection)
                        * 5680 MHz [136] (24.0 dBm) (radar detection)
                        * 5700 MHz [140] (24.0 dBm) (radar detection)
                        * 5720 MHz [144] (24.0 dBm) (radar detection)
                        * 5745 MHz [149] (30.0 dBm)
                        * 5765 MHz [153] (30.0 dBm)
                        * 5785 MHz [157] (30.0 dBm)
                        * 5805 MHz [161] (30.0 dBm)
                        * 5825 MHz [165] (30.0 dBm)
                        * 5845 MHz [169] (disabled)
                        * 5865 MHz [173] (disabled)
                        * 5885 MHz [177] (disabled)
        valid interface combinations:
```

```
# iw reg get
global
country US: DFS-FCC
        (902 - 904 @ 2), (N/A, 30), (N/A)
        (904 - 920 @ 16), (N/A, 30), (N/A)
        (920 - 928 @ 8), (N/A, 30), (N/A)
        (2400 - 2472 @ 40), (N/A, 30), (N/A)
        (5150 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
        (5250 - 5350 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
        (5470 - 5730 @ 160), (N/A, 24), (0 ms), DFS
        (5730 - 5850 @ 80), (N/A, 30), (N/A), AUTO-BW
        (5850 - 5895 @ 40), (N/A, 27), (N/A), NO-OUTDOOR, AUTO-BW, PASSIVE-SCAN
        (5925 - 7125 @ 320), (N/A, 12), (N/A), NO-OUTDOOR, PASSIVE-SCAN
        (57240 - 71000 @ 2160), (N/A, 40), (N/A)

phy#1 (self-managed)
country US: DFS-FCC
        (2402 - 2472 @ 40), (6, 30), (N/A)
        (5170 - 5250 @ 80), (6, 30), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (6, 24), (0 ms), DFS, AUTO-BW
        (5490 - 5730 @ 160), (6, 24), (0 ms), DFS, AUTO-BW
        (5735 - 5895 @ 160), (6, 30), (N/A), AUTO-BW

phy#0 (self-managed)
country US: DFS-FCC
        (2402 - 2472 @ 40), (6, 30), (N/A)
        (5170 - 5250 @ 80), (6, 30), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (6, 24), (0 ms), DFS, AUTO-BW
        (5490 - 5730 @ 160), (6, 24), (0 ms), DFS, AUTO-BW
        (5735 - 5895 @ 160), (6, 30), (N/A), AUTO-BW
```
Note that the "self-managed"  phys show the same info irrespective of `iw reg set`

**Comment by testuser7** [comment]
And that's how it should be. It is possible to limit channels in BDF but it is not done here.

**Comment by robimarko** [comment]
Yeah, iw reg get wont change.

@mrnuke Can you make a PR to limit the frequencies against the main tree and I will merge this then

**Comment by mrnuke** [comment]
@robimarko I need a merged hash for the BFD repo before I can update the PR in main. Won't the automated checks fail ohterwise?

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by robimarko** [comment]
@mrnuke Yeah, you are right, merged this so you can do it.

**Pull request merged**
