### PR TITLE
ipq8074: add Spectrum SAX1V1K BDF

### PR DESCRIPTION
**Pull request by gotofbi**
ipq8074: add Spectrum SAX1V1K BDF
https://forum.openwrt.org/t/spectrum-sax1v1k-askey-rt5010w-openwrt-support/149923

```
FileSize: 131180
FileCRC32: 1544fc98
FileMD5: da5aeb530a8c890c77bda89232737f31
BoardNames[0]: 'bus=ahb,qmi-chip-id=0,qmi-board-id=255,variant=Spectrum-SAX1V1K'
BoardLength[0]: 131072
BoardCRC32[0]: f157dd6e
BoardMD5[0]: c3d2f810f6490e7ab88cf64e8938f724
```

### CODE REVIEW

**Comment by gotofbi** [comment]
@Ansuel @robimarko

Can someone please review?

**Comment by SpectreDev1** [comment]
LGTM but I can't do anything

**Comment by testuser7** [comment]
The description and `Signed-off-by` are missing in the commit.

**Comment by gotofbi** [comment]
> The description and `Signed-off-by` are missing in the commit.

fixed!

**Comment by testuser7** [comment]
> fixed!

The description may be more general, check other commits.

**Comment by gotofbi** [comment]
> > fixed!
> 
> The description may be more general, check other commits.

fixed!!
referenced https://github.com/openwrt/firmware_qca-wireless/pull/30

**Comment by Fil010** [comment]
Tested after having it on for a long time
`Tested-by: Francisco G Luna <frangonlun@gmail.com>`

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by dangerweenie** [comment]
working well over here, have had a few WAN dropouts but going to restart

**Pull request merged**
