### PR TITLE
ipq8074: add Askey RT5010W-D187 BDF

### PR DESCRIPTION
**Pull request by gotofbi**
ipq8074: add Askey RT5010W-D187 BDF
https://forum.openwrt.org/t/spectrum-sax1v1k-askey-rt5010w-openwrt-support/149923
https://github.com/MeisterLone/Askey-RT5010W-D187-REV6/tree/master/BoardFW

### CODE REVIEW

**Comment by SpectreDev1** [comment]
wrong commit name should be `IPQ8072A`, clean up the PR there shouldnt be a merge branch into branch commit

**Comment by SpectreDev1** [comment]
You can do git rebase and fix it

**Comment by gotofbi** [comment]
> wrong commit name should be `IPQ8072A`, clean up the PR there shouldnt be a merge branch into branch commit

which name are you referring to?

**Comment by SpectreDev1** [comment]
> > wrong commit name should be `IPQ8072A`, clean up the PR there shouldnt be a merge branch into branch commit
> 
> which name are you referring to?

Your commit name

**Comment by gotofbi** [comment]
> > > wrong commit name should be `IPQ8072A`, clean up the PR there shouldnt be a merge branch into branch commit
> > 
> > 
> > which name are you referring to?
> 
> Your commit name

Sorry, Im super confused,
I thought it is common to call ipq8074 although its ipq8072a
ref : https://github.com/openwrt/firmware_qca-wireless/pull/20
ref : https://github.com/openwrt/firmware_qca-wireless/pull/11

**Comment by SpectreDev1** [comment]
Yeah ok leave it as IPQ8074 and just get rid of merg commit

**Comment by gotofbi** [comment]
sorry, i messed up this pr and cannot reopen it anymore.
so I created new pr.
https://github.com/openwrt/firmware_qca-wireless/pull/36

**Pull request closed without merging**
