### PR TITLE
qca4019 and qca9888: Add Netgear LBR20 two BDF's

### PR DESCRIPTION
**Pull request by MiG-41**
Files QCA4019 hw1.0 and QCA9888 hw2.0  been exracted from Netgear's LBR20 firmware , and treated with qca-swiss-army-knife:
For QCA4019 hw1.0
bus=ahb,bmi-chip-id=0,bmi-board-id=20,variant=Netgear-LBR20
bus=ahb,bmi-chip-id=0,bmi-board-id=21,variant=Netgear-LBR20
and created a file:
board-netgear_lbr20.qca4019

For QCA9888 hw2.0
bus=pci,bmi-chip-id=0,bmi-board-id=17,variant=Netgear-LBR20
and created a file:
board-netgear_lbr20.qca9888

LBR20 have 3 radios:
radio0 : in qca9888 5Ghz low channels
radio1: in ipq4019 2,4Ghz
radio2: in ipq 4019 5Ghz high channels

### CODE REVIEW

**Comment by MiG-41** [comment]
> Please change the commit title to something similar to device support commit and please add a description as well.

Done , is it ok ?

**Comment by robimarko** [comment]
Just add the `ipq40xx` prefix as well

**Comment by MiG-41** [comment]
> Just add the `ipq40xx` prefix as well

Done

**Comment by robimarko** [comment]
Merged via https://github.com/openwrt/firmware_qca-wireless/commit/10279ccfdab2f7377d0e1ea60a2db9d7d6c85c92

Thanks

**Pull request closed without merging**
